[primary]
192.168.0.178

[workers]
192.168.0.156
192.168.0.45

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=administrator
ansible_ssh_pass=Password01
ansible_become_pass=ModularityCafe!