apiVersion: v1
kind: ConfigMap
metadata:
  name: filestore-config
  namespace: filestore
data:
  config.yaml: |
    host: 0.0.0.0
    port: 5000
    base_url: http://files.dexidevs.net
    max_upload_mb: 10
    token_length: 5
    s3_endpoint: https://192.168.0.145:30293
    s3_region: us-east-1
    s3_bucket: anonupload
    s3_verify_ssl: false
